import React from 'react'
import { X, ZoomIn, ZoomOut, Maximize2 } from 'lucide-react'
import clsx from 'clsx'

export function DiagramModal({ isOpen, onClose, svgContent, title }) {
  const [scale, setScale] = React.useState(1)

  React.useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden'
      setScale(1)
    } else {
      document.body.style.overflow = 'unset'
    }
    return () => {
      document.body.style.overflow = 'unset'
    }
  }, [isOpen])

  if (!isOpen) return null

  const handleZoomIn = () => setScale(prev => Math.min(prev + 0.2, 3))
  const handleZoomOut = () => setScale(prev => Math.max(prev - 0.2, 0.5))
  const handleReset = () => setScale(1)

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6">
      <div 
        className="absolute inset-0 bg-black/60 backdrop-blur-sm transition-opacity" 
        onClick={onClose}
      />
      
      <div className="relative w-full max-w-5xl h-[85vh] bg-[#0d1117] rounded-xl border border-slate-700 shadow-2xl flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-[#161b22]">
          <div>
            <h3 className="text-lg font-bold text-slate-200">{title || 'Control Flow Graph'}</h3>
            <p className="text-xs text-slate-500 font-mono mt-0.5">Visual Representation</p>
          </div>
          <div className="flex items-center gap-2">
            <div className="flex items-center bg-slate-800/50 rounded-lg p-1 mr-4 border border-slate-700/50">
              <button 
                onClick={handleZoomOut}
                className="p-1.5 text-slate-400 hover:text-slate-200 hover:bg-slate-700 rounded transition-colors"
                title="Zoom Out"
              >
                <ZoomOut size={16} />
              </button>
              <span className="text-xs font-mono text-slate-500 w-12 text-center select-none">
                {Math.round(scale * 100)}%
              </span>
              <button 
                onClick={handleZoomIn}
                className="p-1.5 text-slate-400 hover:text-slate-200 hover:bg-slate-700 rounded transition-colors"
                title="Zoom In"
              >
                <ZoomIn size={16} />
              </button>
              <div className="w-px h-4 bg-slate-700 mx-1" />
              <button 
                onClick={handleReset}
                className="p-1.5 text-slate-400 hover:text-slate-200 hover:bg-slate-700 rounded transition-colors"
                title="Reset View"
              >
                <Maximize2 size={16} />
              </button>
            </div>
            
            <button 
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-white hover:bg-red-500/20 hover:border-red-500/50 border border-transparent rounded-lg transition-all duration-200"
            >
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-auto bg-[#0d1117] p-8 flex items-center justify-center relative">
          <div 
            className="transition-transform duration-200 ease-out origin-center"
            style={{ transform: `scale(${scale})` }}
            dangerouslySetInnerHTML={{ __html: svgContent }} 
          />
        </div>
        
        {/* Footer */}
        <div className="px-6 py-3 bg-[#161b22] border-t border-slate-800 text-xs text-slate-500 flex justify-between items-center">
          <span className="font-mono">Generated by Graphviz</span>
          <span className="font-mono">Scroll to pan • Ctrl+Scroll to zoom</span>
        </div>
      </div>
    </div>
  )
}
