import React, { useEffect, useState } from 'react';
import { Graphviz } from 'graphviz-react';
import { X, ZoomIn, ZoomOut, Maximize } from 'lucide-react';

export function DiagramViewer({ dotSource, onClose }) {
  const [scale, setScale] = useState(1);

  // Reset scale when dotSource changes
  useEffect(() => {
    setScale(1);
  }, [dotSource]);

  if (!dotSource) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-in fade-in duration-200">
      <div className="bg-[#0d1117] border border-slate-700 rounded-xl shadow-2xl w-full max-w-6xl h-[85vh] flex flex-col overflow-hidden">
        
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-[#161b22]">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-purple-500/10 rounded-lg">
              <Maximize size={20} className="text-purple-400" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-200">Control Flow Graph</h2>
              <p className="text-xs text-slate-500 font-mono">Visualizing algorithm logic</p>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            <button 
              onClick={() => setScale(s => Math.min(s + 0.1, 2))}
              className="p-2 hover:bg-slate-800 rounded-lg text-slate-400 hover:text-white transition-colors"
              title="Zoom In"
            >
              <ZoomIn size={20} />
            </button>
            <button 
              onClick={() => setScale(s => Math.max(s - 0.1, 0.5))}
              className="p-2 hover:bg-slate-800 rounded-lg text-slate-400 hover:text-white transition-colors"
              title="Zoom Out"
            >
              <ZoomOut size={20} />
            </button>
            <div className="w-px h-6 bg-slate-700 mx-2" />
            <button 
              onClick={onClose}
              className="p-2 hover:bg-red-500/10 hover:text-red-400 rounded-lg text-slate-400 transition-colors"
            >
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Canvas */}
        <div className="flex-1 overflow-auto bg-slate-50 relative flex items-center justify-center p-8">
            <div 
              style={{ 
                transform: `scale(${scale})`, 
                transition: 'transform 0.2s ease-out',
                transformOrigin: 'center center'
              }}
              className="graphviz-container"
            >
              <Graphviz 
                dot={dotSource} 
                options={{
                  fit: true,
                  height: '100%',
                  width: '100%',
                  zoom: false,
                }}
              />
            </div>
        </div>
        
        {/* Footer */}
        <div className="px-6 py-3 border-t border-slate-800 bg-[#161b22] flex justify-between items-center text-xs text-slate-500 font-mono">
           <span>Generated by Algo.Analyzer</span>
           <span>Scale: {Math.round(scale * 100)}%</span>
        </div>
      </div>
    </div>
  );
}
