@echo off
echo Starting Complexity Analyzer...
echo Starting Backend (FastAPI)...
start "Backend" cmd /k ".venv\Scripts\python.exe -m uvicorn src.server.main:app --reload --host 0.0.0.0 --port 8000"
echo Starting Frontend (Vite)...
start "Frontend" cmd /k "cd web_app && npm run dev"
echo Done! Access the app at http://localhost:5173
